repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types:
            - python
        args:
            - --safe
            - --quiet
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types:
            - python
        exclude: tests/
        always_run: true
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        pass_filenames: false
        always_run: true
        language: system
